WSEIWebApp.Web/Entities/ItemEntity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WSEIWebApp.Web.Entities
{
    public class ItemEntity
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsVisible { get; set; }
    }
}

WSEIWebApp.Web/Models/AddNewItemConfirmationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WSEIWebApp.Web.Models
{
    public class AddNewItemConfirmationViewModel
    {
        public int Id { get; internal set; }

        public string Name { get; internal set; }
    }
}

WSEIWebApp.Web/Models/AddNewItemResponseModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WSEIWebApp.Web.Models
{
    public class AddNewItemResponseModel
    {
        public string Message { get; set; }
        public bool Success { get; set; }
    }
}

WSEIWebApp.Web/Models/CompanyAddedViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WSEIWebApp.Web.Models
{
    public class CompanyAddedViewModel
    {
        public int NumberOfCharsInName { get; set; }

        public int NumberOfCharsInDescription { get; set; }

        public bool IsHidden { get; set; }
    }
}

WSEIWebApp.Web/Models/CompanyModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WSEIWebApp.Web.Models
{
    public class CompanyModel
    {
        public string Name { get; set; }

        public string Description { get; set; }

        public bool IsVisible { get; set; }
    }
}

WSEIWebApp.Web/Models/ErrorViewModel.cs
using System;

namespace WSEIWebApp.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WSEIWebApp.Web/Models/ItemModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WSEIWebApp.Web.Models
{
    public class ItemModel
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsVisible { get; set; }
    }
}

WSEIWebApp.Web/Controllers/ActionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using WSEIWebApp.Web.Models;
using Microsoft.AspNetCore.Mvc;
using WSEIWebApp.Web.Database;
using WSEIWebApp.Web.Entities;

namespace WSEIWebApp.Web.Controllers
{
    [ApiController]
    [Route("api/ActionController")]
    public class ActionController : ControllerBase
    {
        private readonly ExchangesDbContext _dbContext;
        public ActionController(ExchangesDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        [HttpPost]
        public AddNewItemResponseModel Post(ItemModel item)
        {
            var entity = new ItemEntity
            {
                Name = item.Name,
                Description = item.Description,
                IsVisible = item.IsVisible,

            };
            _dbContext.Items.Add(entity);
            _dbContext.SaveChanges();

            return new AddNewItemResponseModel
            {
                Message = $"{item.Name} was added",
                Success = true
            };
        }    
    }
}

WSEIWebApp.Web/Controllers/AddItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WSEIWebApp.Web.Models;
using WSEIWebApp.Web.Entities;
using WSEIWebApp.Web.Database;

namespace WSEIWebApp.Web.Controllers
{
    public class AddItemController : Controller
    {
        private readonly ExchangesDbContext _dbContext;
        public AddItemController(ExchangesDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public IActionResult ShowItems()
        {
            var items = _dbContext.Items.ToArray<ItemEntity>();

            return View("~/Views/Items/ShowItems.cshtml", items);
        }
        [HttpGet]
        public IActionResult AddItem()
        {
            return View("~/Views/Items/AddItem.cshtml");
        }

        [HttpPost]
        public IActionResult AddItem(ItemModel item)
        {
            return RedirectToAction("AddConfirmation");
        }

        [HttpGet]
        public IActionResult AddConfirmation()
        {
            return View("~/Views/Items/AddConfirmation.cshtml");
        }
    }
}

WSEIWebApp.Web/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WSEIWebApp.Web.Models;

namespace WSEIWebApp.Web.Controllers
{
    public class CompanyController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]

        public IActionResult Index(CompanyModel company)
        {
            var viewModel = new CompanyAddedViewModel
            {
                NumberOfCharsInName = company.Name.Length,
                NumberOfCharsInDescription = company.Description.Length,
                IsHidden = !company.IsVisible
            };

            return View("CompanyAdded", viewModel);
        }
    }
}

WSEIWebApp.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WSEIWebApp.Web.Models;

namespace WSEIWebApp.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult AddItem()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WSEIWebApp.Web/Views/Company/CompanyAdded.cshtml
@model CompanyAddedViewModel

<h1> Your Company was successfully added!</h1>

<h5> Some stats:</h5>

<div> Chars in Name: @Model.NumberOfCharsInName</div>
<div> Chars in Description: @Model.NumberOfCharsInDescription</div>
<div> Is the Company currently hidden: @(Model.IsHidden ? "yes" : "no")</div>

WSEIWebApp.Web/Views/Company/Index.cshtml
@model CompanyModel

<h1> Company management</h1>

<h2> Add new company</h2>

@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(x => x.Name, "Company name")
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Description, "Company description")
        @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.CheckBoxFor(x => x.IsVisible, new { @class = "form-check-input" })
        @Html.LabelFor(x => x.IsVisible, "Visible?", new { @class = "form-check-label" })
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Add Company</button>
    </div>
}

WSEIWebApp.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <vc:latest-item />
</div>

WSEIWebApp.Web/Views/Items/AddConfirmation.cshtml
@model AddNewItemConfirmationViewModel

<h2>Add new item</h2>

<p>Congratulations!</p>

@*<p>Your new item "@Model.Name" was successfully added to the system with the ID @Model.Id</p>*@
<p>Your item was added</p>

WSEIWebApp.Web/Views/Items/AddItem.cshtml
@model ItemModel

<div id="success-alert" class="alert alert-success" style="display: none">Item added successfully</div>

<h2>Add new item</h2>

    <form method="POST">
        <div class="form-group">
            <label asp-for="Name">Item name</label>
            <input asp-for="Name" class="form-control" id="add-name" />
        </div>

        <div class="form-group">
            <label asp-for="Description">Description</label>
            <input asp-for="Description" class="form-control" id="add-desc" />
        </div>

        <div class="form-check">
            <input asp-for="IsVisible" class="form-check-input" id="add-visible" />
            <label asp-for="IsVisible" class="form-check-label">Item visible?</label>
        </div>

        <div class="form-group">
            <input type="submit" value="Add new item" />
        </div>

    </form>


@section Scripts {
    <script src="~/js/addNewItem.js?v=136"></script>
}

WSEIWebApp.Web/Views/Items/ShowItems.cshtml
@model WSEIWebApp.Web.Entities.ItemEntity[]
<h2>Database items</h2>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">IsVisible</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@item.Id</th>
                <td>@item.Name</td>
                <td>@item.Description</td>
                <td>@item.IsVisible</td>
            </tr>
        }
    </tbody>
</table>

WSEIWebApp.Web/Views/Shared/Components/LatestItem/Default.cshtml
@model WSEIWebApp.Web.Entities.ItemEntity
<div>Latest item added: @Model.Name</div>

WSEIWebApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WSEIWebApp.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WSEIWebApp.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AddItem" asp-action="AddItem">Add Item</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AddItem" asp-action="ShowItems">Show Items</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - WSEIWebApp.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>